### ISSUE TITLE
Invalid range error

### ISSUE THREAD

**Issue by Toshegg** [AndrewRadev/inline_edit.vim#23]
Hello!

I'm using neovim
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/config -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/include
Compiled  brew@HighSierra-2.local
```

When I'm opening inline edit buffer, leaving it and then returning back, it displays certain errors:

![image](https://user-images.githubusercontent.com/5630034/34200782-ff7be2da-e57a-11e7-8e95-ed43c5b48d3d.png)

On the other hand, with option `let g:inline_edit_proxy_type = 'tempfile'` everything works perfect, but filename in that case seems to be uninformative.

Also, according to https://github.com/AndrewRadev/inline_edit.vim/issues/15 issue I've tried to execute `:file` command (without proxy_type: tempfile) and it displays a value without any error:
`"[my-file.html:205-1393]" [Not edited] 1189 lines --99%--`

Can you please help me to solve this annoying problem?

**Comment by AndrewRadev** [comment]
I installed neovim, but I can't reproduce the issue. Could you explain what the steps are for you to get the error? For instance, could you give me a sample HTML file (for example) and then go over the steps, for instance:

- First you edit the html file
- Go in a `script` tag, start `:InlineEdit`
- Change the buffer and `:write`
- ...

And so on. For instance, I'm not sure what leaving the buffer and returning back means -- do you jump around, or do you mean hiding it and then showing it? If I had an idea, I could try replicating the problem more effectively.

**Comment by Toshegg** [comment]
@AndrewRadev, seems like this issue is caused by https://github.com/neomake/neomake, which is trying to run linter on the file, which does not exist.
I have this command in my vimrc:
`autocmd! BufEnter,BufWritePost * Neomake`
Is there any way to distinguish inline_edit's buffer from a regular file and make some additions to this command to avoid execution of neomake in those buffers?

**Comment by AndrewRadev** [comment]
Ah, I see, that explains it.

An inline-edited proxy buffer will have a variable called `b:proxy` in it. So I'd guess what you could do is change that line to:

``` vim
autocmd! BufEnter,BufWritePost * if !exists('b:proxy') | Neomake | endif
```

Also, I now realize maybe the variable should have been called `b:inline_edit_proxy`? I'm not sure if I shouldn't just change it now. I can't remember if I've given people the advice to use it, it might break something :/.

For starters, does this fix the issue for you? And if so, do you think I should change the name of this buffer-local variable?

**Comment by AndrewRadev** [comment]
Excellent. I've renamed the variable `b:inline_edit_proxy`, but I've left `b:proxy` as an alias just in case somebody out there is using it. I feel like it's probably not breaking anything, though if, at some point, somebody writes to me about polluting the buffer's namespace, I might remove it.

Either way, you can change that if-clause to use `b:inline_edit_proxy`, would be easier to read that code at a later time.

**Comment by Toshegg** [comment]
@AndrewRadev, by the way, maybe it does not refer to your plugin, but is it possible to make the split buffer work with neomake?

**Comment by AndrewRadev** [comment]
Well, as you noticed with the "tempfile" buffer type, that one works. The reason is that the "scratch" one just uses a buffer that is not connected to an underlying file. Neomake probably executes some linter on the *file*, but there is no file. If you set the buffer type to "tempfile", it should work, because that one creates an explicit file in `/tmp`, giving neomake something on the filesystem to work with.

You mentioned that in the "tempfile" case the filename is uninformative. One thing I do to improve this is change the statusline. If the `statusline` setting includes `%f` or `%F` to show the file path somewhere, I substitute that with the filename description with the line numbers. Might be that you could adjust your statusline to get this to work right? If you're using a plugin, maybe you can squeeze in the description yourself? The code would look something like this, probably:

``` vim
let short_filename = fnamemodify(b:inline_edit_proxy.original_buffer, ':~:.')
let statusline = printf('[%s:%%{b:inline_edit_proxy.start}-%%{b:inline_edit_proxy.end}]', short_filename)
```

**Comment by Toshegg** [comment]
Thank you, worksforme, but another thing is that neomake should take right linter settings from a file in a current directory, which is `/tmp` in case of `tempfile`. Is there some way to create this file in the current working directory (in `./.tmp/` directory, for instance) and remove it when the buffer closes?

**Comment by AndrewRadev** [comment]
Hmm, that seems a bit of a complicated workaround. Right now, the plugin just creates a file using the built-in `tempname()` function. This is a pretty reliable method, given problems like permissions, readability and such. Creating a new directory next to the file might also trigger file watchers or something, causing possible unintended effects?

If neomake takes linter settings from the "current directory", shouldn't it take them from the current working directory, instead of relative to the file? It doesn't seem plausible that every file in a nested directory has a nearby config file. Or is it that it looks upwards for a file? Could you point me to the relevant documentation for configuration settings in the neomake docs or wiki or something? I might be able to figure something else out.

**Comment by Toshegg** [comment]
Ok, I've solved this by installing linter globally, everything works now in inline_edit's temp file as well.
But now I faced with another strange issue:
As you maybe remember, I'm using `autocmd! BufEnter,BufWritePost * Neomake` to call linter automatically after a file is loaded. But when I call `:InlineEdit` for the first time, it opens new split, but this hook doesn't trigger for some reason. I should either enter this buffer again or call `:Neomake` manually. Which hook should I use in this case?
Also, I have some problems with airline, when I open split for the first time (on the bottom of the split):
![image](https://user-images.githubusercontent.com/5630034/34437487-5cb9c696-eca7-11e7-99ff-4cb860bc2d96.png)
And this is how it should look like:
![image](https://user-images.githubusercontent.com/5630034/34437502-76821eac-eca7-11e7-8ec1-ac14dddc045e.png)
It looks correctly only after I leave the split and focus it again or if I resize terminal (so, I assume that this issue maybe somehow related to redrawing, but I've tried even without `set lazyredraw` and it reproduces).

**Comment by AndrewRadev** [comment]
I assume it's due to the interaction between airline and my overriding of the statusline. I guess it's harder than I'd thought :).

I've just pushed some commits to help with this, but you'll need to change a setting. Put this in your vimrc:

``` vim
let g:inline_edit_modify_statusline = 0
```

With this, you'll be getting a funky temporary name again. You can fix this through airline's API -- in the buffer, the `b:inline_edit_proxy` variable should be available. Using `b:inline_edit_proxy.description` will give you a sensible-looking file description, but you'll have to figure out how to put this in airline. Probably something like...

``` vim
function! AirlineInit()
  if exists('b:inline_edit_proxy')
    let g:airline_section_b = airline#section#create_left(["ffenc", "hunks", "%{b:inline_edit_proxy.description}"])
  else
      let g:airline_section_b = airline#section#create_left(["ffenc", "hunks", "%f"])
  endif
endfunction
```

But I'm kind of guessing based on the airline docs, I can't really say if this will work or if you need something different.

**Comment by Toshegg** [comment]
Thank you, this works! And what about `:Neomake` trigger? Which hook should I use instead of `BufEnter,BufWritePost`?

**Comment by AndrewRadev** [comment]
Sorry for taking a while to respond. I couldn't find the time to work on my Vim plugins for quite a while.

Unfortunately, I don't know what the problem is in this case. Here's the two autocommands that are being executed in the plugin: https://github.com/AndrewRadev/inline_edit.vim/blob/58c0b6929492cd45e9aca18fce72316c90404036/autoload/inline_edit/proxy.vim#L28-L32

So, either `BufWritePost`, or `BufWriteCmd`, depending on the type of proxy buffer. Which proxy type are you seeing the issue in? The "tempfile" one? I guess the other one wouldn't really work with neomake, as we discussed.

It might be that the two autocommands are interfering, although it really shouldn't be the case. You could try commenting that line in the plugin and see if the `:Neomake` gets called on write, just to figure out if that's the problem somehow.
