### ISSUE TITLE
Filetype match in markdown should be case-insensitive

### ISSUE THREAD

**Issue by kapral18** [AndrewRadev/inline_edit.vim#31]
Hi

currently https://github.com/AndrewRadev/inline_edit.vim/blob/b5bff636fd2ca9d00ba0001398159f47145a8cdf/autoload/inline_edit.vim#L62

matches whatever is in the line with registered filetypes, this leads to innocent declarations like

````Dockerfile` to blow up with cryptic error message like

![CleanShot 2023-10-23 at 09 29 13@2x](https://github.com/AndrewRadev/inline_edit.vim/assets/1625373/1e94fcff-3230-4190-9f6d-e8e4ce3ca6ec)

and then it still opens the dockerfile snippet which gets proper syntax highlighting still

So I suggest to wrap the `getLine()` in `tolower()` to make sure this doesn't happen since in markdown you can use any casing
and most parsers consume it without problem.

What do you think?

I can push the PR if you want

**Comment by AndrewRadev** [comment]
Thanks for reporting. I'm actually not sure why it's erroring out, because if you use `Dockerfile` prefixed with three backticks, at least for me, it sets it to `Dockerfile`. Which is wrong, because of the casing, but it doesn't error out. It *does* error out if I put *four* backticks, so I've adjusted the regex to make sure that the character after 3 backticks is a keyword character. I've also added the `tolower` as you suggested, since the filetype is actually "dockerfile".

Could you try it out now and let me know if the error is avoided? Does it correctly set the filetype?

**Comment by kapral18** [comment]
@AndrewRadev weidly it still errors but only at the start of nvim, no longer errors after repeated inline-edit invocation.

Here is my config https://github.com/kapral18/config.nvim/blob/5d7bb88768250bdc2bcf3254aa21fe6831237794/lua/plugins/inline-edit.lua

And here is the snippet of md file

```md
.```Dockerfile
FROM leaseplan.jfrog.io/art-0055-docker-virtual/leaseplan/frontend-server:2

ENV FE_SERVER_PUBLIC_ROOT=/build

COPY /path/to/static/build /build

EXPOSE 3000
.```

```
P.S. disregard the (.) I was trying to escape the ` ``` ` block

**Comment by AndrewRadev** [comment]
Yeah, escaping this stuff is tricky, I'm assuming it looks something like this: 
![2023-10-25-131613_1920x1080_scrot](https://github.com/AndrewRadev/inline_edit.vim/assets/124255/00c9aa89-82a4-4279-b688-d3ee2ae8a5b6)

I can't replicate the issue on Vim or on Neovim with vim-plug. Since it only happens on startup, it feels like a lazy-loading problem, but I don't see what would be the cause. There's no autocommands that need to be set up, I think. Could you check these things on your setup:

- Does the problem still occur with `lazy = false`?
- Does it happen with the keybinding you've setup, and/or with the `:InlineEdit` command? (could be something to do with the way `<cmd>` is evaluated, just want to check)

I'll try to allocate some time to install lazy.nvim to try this out, or maybe clone your config, but it might have to wait for the weekend.

**Comment by AndrewRadev** [comment]
Update: I set up lazy.nvim according to the instructions in the README and I copied your config. I am getting an error, but it's "Lua module not found for config of inline_edit.vim. Please use a `config()` function instead". Which I'm guessing happens due to the `config = true` in the configuration table. Removing `config = true` also avoids the error, and the plugin seems to load and work fine. Is that the error you're currently seeing?

**Comment by kapral18** [comment]
@AndrewRadev turns out I need to remove config() or config=true altogether, since config is for lua based plugins only, but thanks for checking

**Comment by kapral18** [comment]
Solved thanks
